#!/bin/bash

# Основные переменные
user="skype"    # пользователь из под которого будет запускаться приложение
command="skype &"    # программа, которая будет запускаться в фоне

start_command="/usr/bin/xvfb-run -f /tmp/${user}.xvfb.auth $command"

# Проверяем имя пользователя. Если оно не совпадает с $user, то запускаем с помощью "su".
# Это необходимо для правильного запуска из под пользователя root (например, при старте системы)

if ( [ "$(whoami)" = "$user" ] ) then
        bash -c "$start_command"
else
        su -c "$start_command" -l $user
fi
