######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 17 18:55:18 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += skype.h \
    skype.h
SOURCES += main.cpp skype.cpp

QT += dbus
