######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 17 18:55:06 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tester_skype.h \
    ../../src/skype.h
SOURCES += tester_skype.cpp \
    ../../src/skype.cpp


QT += testlib
QT += dbus
